{{- if .Values.externalSecrets }}
{{- $fullName := include "backendService.fullname" . -}}
{{- $labels := include "backendService.labels" . -}}

{{- range $k := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $fullName }}-{{ $k.keyvaultName }}
  labels:
    keyvault-name: {{ $k.keyvaultName }}
    {{- $labels | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: {{ $k.identityId }}
      tenantId:  {{ $k.tenantId }}
      vaultUrl: {{ $k.keyvaultURL | default (printf "https://%s.vault.azure.net" $k.keyvaultName) }}
---
{{- range $v := $k.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $v.name }}
  labels:
    secret-store: {{ $k.keyvaultName }}
    {{- $labels | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $fullName }}-{{ $k.keyvaultName }}

  target:
    name: {{ $v.name }}
    creationPolicy: Owner

    template:
      type: {{ $v.type }}

      metadata:
        annotations:
{{ toYaml $v.metadata.annotations | indent 10 }}
        labels:
{{ toYaml $v.metadata.labels | indent 10 }}

  data:
  {{- range $d := $v.data }}
  - secretKey: {{ $d.key }}
    remoteRef:
      key: {{ $d.objectName }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}