{{/* SPDX-SnippetBegin */}}
{{/* SPDX-License-Identifier: Apache License 2.0 */}}
{{/* SPDX-SnippetCopyrightText: 2024 © Grafana, grafana/helm-charts */}}
{{/* SPDX-SnippetCopyrightText: 2024 © Unique AG */}}
{{/* SPDX-SnippetEnd */}}
{{- $hasEnabledRoutes := false }}
{{- range $name, $route := .Values.extraRoutes }}
  {{- if $route.enabled }}
    {{- $hasEnabledRoutes = true }}
  {{- end }}
{{- end }}
{{- if $hasEnabledRoutes }}
{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" }}
{{- range $name, $route := .Values.extraRoutes }}
  {{- if $route.enabled }}
---
apiVersion: {{ $route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: {{ $route.kind | default "HTTPRoute" }}
metadata:
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "backendService.fullname" $ }}-{{ $name }}
  labels:
    {{- include "backendService.labels" $ | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if $route.additionalRules }}
    {{- tpl (toYaml $route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ include "backendService.fullname" $ }}
          port: {{ include "backendService.servicePort" $ }}
          kind: Service
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- else }}
{{- fail "You can't use extraRoutes without CRDs installed. Install CRDs first."}}
{{- end }}
{{- end }}
