{{- if .Values.pdb }}
{{- if or (gt (int .Values.replicaCount) 1) (and .Values.autoscaling.enabled (gt (int .Values.autoscaling.minReplicas) 1)) }}
{{- if and (not .Values.pdb.maxUnavailable) (not .Values.pdb.minAvailable) }}
{{- fail "You must either set `.Values.pdb.maxUnavailable` or `.Values.pdb.minAvailable` when there is more than 1 replica configured." }}
{{- else }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backendService.fullname" . }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backendService.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}