{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backendService.fullname" . }}
  labels:
    {{- include "backendService.serviceLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "backendService.servicePort" . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ports.metrics }}
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "backendService.selectorLabels" . | nindent 4 }}
{{- end }}
