#
# EXAMPLE VALUES FOR EXTRA CRONJOBS
# Uses cronJob and extraCronJobs to define a CronJob and an extra CronJob
#
env:
  FOO: quux
extraCronJobs:
  foo:
    concurrencyPolicy: Forbid
    env:
      FOO: BAR
    envVars:
      - name: BAZ
        value: qux
    failedJobsHistoryLimit: 3
    restartPolicy: Never
    schedule: 0 0 1 1 *
    startingDeadlineSeconds: 600
    successfulJobsHistoryLimit: 3
    suspend: false
    timeZone: Europe/Zurich
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
image:
  repository: "ghcr.io/unique-ag/chart-testing-service"
  tag: "1.0.4"
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
