# -- routes is a special object designed for Unique services. It abstracts a lot of complexity and allows for a simple configuration of routes.
# ⚠️ Unique defaults to Kong as its API Gateway (the middlewares especially), and the routes object is designed to work with Kong. If you are using a different API Gateway, you will need to use `extraRoutes`.
# Refer to [`ci/routes-values.yaml`](https://github.com/Unique-AG/helm-charts/blob/main/charts/backend-service/ci/routes-values.yaml) to see a full example of how to configure routes.
routes:
  # - hostname of the route, will be matched against the host header of the request
  # currently defaults to one, if ever more are needed open an issue, `extraHostNames` will be added, supports templating
  hostname: chart-testing-service.example.com
  # -- gateway to use
  gateway:
    # -- name of the gateway
    # @default -- kong
    name: kong
    # -- namespace of the gateway
    # @default -- system
    namespace: system
  # -- pathPrefix allows setting the default prefix (fullname) for all paths
  # @default -- defaults to the fullname of the service
  pathPrefix: ""
  paths:
    default:
      enabled: true
      blockList:
        - /metrics
        - /sensitive
      extraAnnotations: []
      #   konghq.com/request-buffering: "false"
      #   konghq.com/read-timeout: "120s"
    versioned:
      enabled: true
      # -- users wishing to not call their versioned API 'public' can override the path
      # ⚠️ Customizing this value requires also changing the default url in multiple places including all SDK or integration use cases
      # @default -- the chart will default to 'public' to stay backward compatible
      pathOverride: /public
      extraAnnotations: []
      #   konghq.com/request-buffering: "false"
    scoped:
      enabled: true
      # -- users wishing to not call their scoped API 'scoped' can override the path
      # ⚠️ Customizing this value requires also changing the default url in multiple places including all web-apps
      # @default -- the chart will default to 'scoped' to stay backward compatible
      pathOverride: /scoped
      # -- explicitly list of exact path matches
      # will be rendered to: `/{scoped|pathOverride}/{entry}`
      allowList:
        - /upload
        - /download
      extraAnnotations: []
      #   konghq.com/request-buffering: "false"
    # -- `/probe` is unauthorized and its sole purpose is to expose a health check endpoint for availability monitoring
    # Maps to version neutral `/probe` endpoint all Unique services expose
    probe:
      enabled: true
      extraAnnotations: []
      #   konghq.com/strip-path: "true"
